export const ADMIN_ACTIONS = {
  VIEW_BOOKING_DETAIL: 'VIEW_BOOKING_DETAIL',
  CANCEL_BOOKING: 'CANCEL_BOOKING',
  FILTER_BOOKING: 'FILTER_BOOKING',
  SEARCH_BOOKING: 'SEARCH_BOOKING',
  TOGGLE_BOOKING_STATUS: 'TOGGLE_BOOKING_STATUS',
  UPDATE_BOOKING: 'UPDATE_BOOKING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  ADMIN_VIEW_BOOKINGS: 'ADMIN_VIEW_BOOKINGS',
} as const;

export type AdminAction = (typeof ADMIN_ACTIONS)[keyof typeof ADMIN_ACTIONS];
